### ISSUE TITLE
Pagination could be a little bit more robust

### ISSUE THREAD

**Issue by TobiX** [gabrie-allaigre/java-gitlab-api#1]
Just an idea:

When I used the sonar-gitlab-plugin with a slightly misconfigured GitLab, pagination built broken URLs:

[removeAPIUrl](https://github.com/gabrie-allaigre/java-gitlab-api/blob/66ff8efaddf2feca47c82b886c521f5ef4104eff/src/main/java/com/talanlabs/gitlab/api/GitLabAPI.java#L117-L119) removed a fixed substring, disregarding the fact that URLs returned from the GitLab server might differ from the configured URL. In my case, this was the difference:

```
Configured: https://git.mycompany.com/
Returned:   https://git.mycompany.com:80/api/v3/projects?archived=false&order_by=created_at&page=2&per_page=20&simple=false&sort=desc
Calculated: https://git.mycompany.com/api/v3/v3/projects?archived=false&order_by=created_at&page=2&per_page=20&simple=false&sort=desc
```

Maybe it would be better to parse the URL, use only the path and remove just the fixed API path prefix instead?

**Comment by gabrie-allaigre** [comment]
Hi,
Thanks.
